spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enabled: true
        erviceId: config-server
  rabbitmq:
    host: localhost
    port: 5672
#   username:
#   password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8881


 